services:
  93athome:
    build:
      context: .
      dockerfile: Dockerfile-CN
    volumes:
      - ./certificates:/app/certificates
      - ./files:/app/files
      - ./data:/app/data
      - ./stats:/app/stats
      - ./plugins:/app/plugins
      - ./assets:/app/assets
    env_file:
      - .env
    environment:
      - IS_IN_DOCKER=true
    network_mode: host
    restart: unless-stopped