services:
  93athome:
    image: saltwood233/open93athome
    volumes:
      - ./files:/app/files
      - ./data:/app/data
      - ./stats:/app/stats
      - ./plugins:/app/plugins
      - ./assets:/app/assets
    env_file:
      - .env
    environment:
      - IS_IN_DOCKER=true
      - TZ=Asia/Shanghai
    network_mode: host
    restart: unless-stopped