version: '3'
services:
  93athome:
    image: saltwood233/open93athome
    volumes:
      - ./certificates:/app/certificates
      - ./files:/app/files
      - ./data:/app/data
      - ./stats:/app/stats
      - ./plugins:/app/plugins
    env_file:
      - .env
    environment:
      - IS_IN_DOCKER=true
    network_mode: host
    restart: unless-stopped