version: '3'
services:
  93athome:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./certificates:/app/certificates
      - ./files:/app/files
      - ./data:/app/data
    env_file:
      - .env
    network_mode: host
    restart: unless-stopped