services:
  93athome:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./files:/app/files
      - ./data:/app/data
      - ./stats:/app/stats
      - ./plugins:/app/plugins
      - ./assets:/app/assets
      - ./plugin-dependencies:/app/plugin-dependencies
    env_file:
      - .env
    environment:
      - IS_IN_DOCKER=true
      - TZ=Asia/Shanghai
    network_mode: host
    restart: unless-stopped